version: 0.2

env:
  variables:
    HOME: $CODEBUILD_SRC_DIR

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y bc schedtool
  build:
    commands:
      - ./build.sh
