version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            mkdir -p ~/bin
            mkdir -p ~/xenon
            curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run:
          name: Repo init
          command: |
            cd ~/xenon
            git config --global user.name 'Joseph Morant Navarro'
            git config --global user.email 'joseph.morantnavarro@gmail.com'
            git config --global color.ui true
            ~/bin/repo init -u https://github.com/joseph184/platform_manifest.git -b n --depth=1
      - run:
          name: Repo sync
          command: |
            cd ~/xenon
            ~/bin/repo sync -c -j32 --quiet
      - run:
          name: Environment set up
          command: |
            cd ~/xenon
            . build/envsetup.sh
      - run:
          name: Building
          command: |
            cd ~/xenon
            breakfast hydrogen
            brunch hydrogen

      - run:
          name: Space left
          command: df -h
