version: 2
jobs:
  build:
    docker:
      - image: joseph184/buildrom:0.0.2
    steps:
      - checkout
      - run:
          name: Dependencies
          command: sudo apt-get update -y && sudo apt-get install -y bc schedtool
      - run:
          name: Build
          command: ./build.sh