version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: Dependencies
          command: apt-get update -y && apt-get install -y bc schedtool
      - run:
          name: Build
          command: ./build.sh