version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            mkdir -p ~/bin
            curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run:
          name: Repo init
          command: |
            git config --global user.name 'Joseph Morant Navarro'
            git config --global user.email 'joseph.morantnavarro@gmail.com'
            git config --global color.ui true
            export PATH=$PATH:~/bin
            mkdir -p ~/xenon && cd ~/xenon && repo init -u https://github.com/joseph184/platform_manifest.git -b n --depth=1
      - run:
          name: Repo sync
          command: |
            export PATH=$PATH:~/bin
            cd ~/xenon && repo sync -c -n -j 4 --quiet && repo sync -c -l -j 8 --quiet
      - run:
          name: Adding hydrogen device
          command: |
            export PATH=$PATH:~/bin
            cp -r --parents .repo ~/xenon
            cd ~/xenon && repo sync -c -n -j 4 --quiet && repo sync -c -l -j 8 --quiet
      - run:
          name: Breakfast
          command: |
            export PATH=$PATH:~/bin
            cd ~/xenon && . build/envsetup.sh && breakfast hydrogen
      - run:
          name: Space left
          command: df -h
      - run:
          name: Brunch
          command: cd ~/xenon && . build/envsetup.sh && brunch hydrogen