version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./install-dependencies.sh
      - run:
          name: Repo init
          command: ./repo-init.sh
      - run:
          name: Repo sync
          command: ./repo-sync.sh
