version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            mkdir -p ~/bin
            mkdir -p ~/xenon
            curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
            echo $PATH
            export PATH=$PATH:~/bin
            echo $PATH
      - run:
          name: Repo init
          command: |
            git config --global user.name 'Joseph Morant Navarro'
            git config --global user.email 'joseph.morantnavarro@gmail.com'
            git config --global color.ui true
            cd ~/xenon && repo init -u https://github.com/joseph184/platform_manifest.git -b n --depth=1
      - run:
          name: Repo sync
          command: cd ~/xenon && repo sync -c -j32 --quiet
      - run:
          name: Adding hydrogen device
          command: cp -r --parents device/xiaomi/hydrogen ~/xenon
      - run:
          name: Building
          command: cd ~/xenon && . build/envsetup.sh && breakfast hydrogen && brunch hydrogen
      - run:
          name: Space left
          command: df -h
